package com.leppaaho.oskari.citybikewidget;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * Hyphenation for bike station names. We could have tried to use Voikko or write a simple
 * hyphenation algorithm by hand but for now just going with hyphenating all the station names by
 * hand for easiest and best quality implementation. Of course this won't work when the stations
 * change. Falling back to the unhyphenated name if the hyphenated one isn't found.
 *
 * Generated the hyphenations with the Webvoikko Hyphenation service:
 * https://joukahainen.puimula.org/webvoikko/hyphenate.
 */
public class Hyphenation {
    private static final Map<String, String> stationHyphenations;
    static {
        Map<String, String> map = new HashMap<String, String>();
        map.put("Mellstenintie", "Mells\u00ADte\u00ADnin\u00ADtie");
        map.put("Toppelundintie", "Top\u00ADpe\u00ADlun\u00ADdin\u00ADtie");
        map.put("Maistraatintori", "Maist\u00ADraa\u00ADtin\u00ADto\u00ADri");
        map.put("Esterinportti", "Es\u00ADte\u00ADrin\u00ADport\u00ADti");
        map.put("Westendintie", "West\u00ADen\u00ADdin\u00ADtie");
        map.put("Rautatieläisenkatu", "Rau\u00ADta\u00ADtie\u00ADläi\u00ADsen\u00ADka\u00ADtu");
        map.put("Toppelundinportti", "Top\u00ADpe\u00ADlun\u00ADdin\u00ADport\u00ADti");
        map.put("Veturitori", "Ve\u00ADtu\u00ADri\u00ADto\u00ADri");
        map.put("Linnakepolku", "Lin\u00ADna\u00ADke\u00ADpol\u00ADku");
        map.put("Ratapihantie", "Ra\u00ADta\u00ADpi\u00ADhan\u00ADtie");
        map.put("Venttiilikuja", "Vent\u00ADtii\u00ADli\u00ADku\u00ADja");
        map.put("Linnanmäki", "Lin\u00ADnan\u00ADmä\u00ADki");
        map.put("Brahen puistikko", "Bra\u00ADhen puis\u00ADtik\u00ADko");
        map.put("Fleminginkatu", "Fle\u00ADmin\u00ADgin\u00ADka\u00ADtu");
        map.put("Gebhardinaukio", "Geb\u00ADhar\u00ADdi\u00ADnau\u00ADki\u00ADo");
        map.put("Mäkelänkatu", "Mä\u00ADke\u00ADlän\u00ADka\u00ADtu");
        map.put("Vilhonvuorenkatu", "Vil\u00ADhon\u00ADvuo\u00ADren\u00ADka\u00ADtu");
        map.put("Kaivopuisto", "Kai\u00ADvo\u00ADpuis\u00ADto");
        map.put("Lintulahdenkatu", "Lin\u00ADtu\u00ADlah\u00ADden\u00ADka\u00ADtu");
        map.put("Laivasillankatu", "Lai\u00ADva\u00ADsil\u00ADlan\u00ADka\u00ADtu");
        map.put("Näkinsilta", "Nä\u00ADkin\u00ADsil\u00ADta");
        map.put("Kapteeninpuistikko", "Kap\u00ADtee\u00ADnin\u00ADpuis\u00ADtik\u00ADko");
        map.put("Isoisänsilta", "I\u00ADso\u00ADi\u00ADsän\u00ADsil\u00ADta");
        map.put("Viiskulma", "Viis\u00ADkul\u00ADma");
        map.put("Arielinkatu", "A\u00ADrie\u00ADlin\u00ADka\u00ADtu");
        map.put("Sepänkatu", "Se\u00ADpän\u00ADka\u00ADtu");
        map.put("Kalasataman metroasema", "Ka\u00ADla\u00ADsa\u00ADta\u00ADman met\u00ADro\u00ADa\u00ADse\u00ADma");
        map.put("Hietalahdentori", "Hie\u00ADta\u00ADlah\u00ADden\u00ADto\u00ADri");
        map.put("Teurastamo", "Teu\u00ADras\u00ADta\u00ADmo");
        map.put("Designmuseo", "De\u00ADsign\u00ADmu\u00ADse\u00ADo");
        map.put("Päijänteentie", "Päi\u00ADjän\u00ADteen\u00ADtie");
        map.put("Vanha kirkkopuisto", "Van\u00ADha kirk\u00ADko\u00ADpuis\u00ADto");
        map.put("Pernajantie", "Per\u00ADna\u00ADjan\u00ADtie");
        map.put("Teollisuuskatu", "Te\u00ADol\u00ADli\u00ADsuus\u00ADka\u00ADtu");
        map.put("Kasarmitori", "Ka\u00ADsar\u00ADmi\u00ADto\u00ADri");
        map.put("Elimäenkatu", "E\u00ADli\u00ADmä\u00ADen\u00ADka\u00ADtu");
        map.put("Unioninkatu", "U\u00ADni\u00ADo\u00ADnin\u00ADka\u00ADtu");
        map.put("Hollolantie", "Hol\u00ADlo\u00ADlan\u00ADtie");
        map.put("Kanavaranta", "Ka\u00ADna\u00ADva\u00ADran\u00ADta");
        map.put("Paavalinpuisto", "Paa\u00ADva\u00ADlin\u00ADpuis\u00ADto");
        map.put("Merisotilaantori", "Me\u00ADri\u00ADso\u00ADti\u00ADlaan\u00ADto\u00ADri");
        map.put("Haukilahdenkatu", "Hau\u00ADki\u00ADlah\u00ADden\u00ADka\u00ADtu");
        map.put("Senaatintori", "Se\u00ADnaa\u00ADtin\u00ADto\u00ADri");
        map.put("Velodrominrinne", "Ve\u00ADlo\u00ADdro\u00ADmin\u00ADrin\u00ADne");
        map.put("Ritarikatu", "Ri\u00ADta\u00ADri\u00ADka\u00ADtu");
        map.put("Sofianlehdonkatu", "So\u00ADfi\u00ADan\u00ADleh\u00ADdon\u00ADka\u00ADtu");
        map.put("Liisanpuistikko", "Lii\u00ADsan\u00ADpuis\u00ADtik\u00ADko");
        map.put("Arabian kauppakeskus", "A\u00ADra\u00ADbi\u00ADan kaup\u00ADpa\u00ADkes\u00ADkus");
        map.put("Varsapuistikko", "Var\u00ADsa\u00ADpuis\u00ADtik\u00ADko");
        map.put("Arabiankatu", "A\u00ADra\u00ADbi\u00ADan\u00ADka\u00ADtu");
        map.put("Porthania", "Por\u00ADtha\u00ADni\u00ADa");
        map.put("Kaironkatu", "Kai\u00ADron\u00ADka\u00ADtu");
        map.put("Rautatientori / itä", "Rau\u00ADta\u00ADtien\u00ADto\u00ADri / i\u00ADtä");
        map.put("Verkatehtaanpuisto", "Ver\u00ADka\u00ADteh\u00ADtaan\u00ADpuis\u00ADto");
        map.put("Kaisaniemenpuisto", "Kai\u00ADsa\u00ADnie\u00ADmen\u00ADpuis\u00ADto");
        map.put("Intiankatu", "In\u00ADti\u00ADan\u00ADka\u00ADtu");
        map.put("Töölönlahdenkatu", "Töö\u00ADlön\u00ADlah\u00ADden\u00ADka\u00ADtu");
        map.put("Koskelantie", "Kos\u00ADke\u00ADlan\u00ADtie");
        map.put("Rautatientori / länsi", "Rau\u00ADta\u00ADtien\u00ADto\u00ADri / län\u00ADsi");
        map.put("Kuikkarinne", "Kuik\u00ADka\u00ADrin\u00ADne");
        map.put("Kiasma", "Ki\u00ADas\u00ADma");
        map.put("Käpyläntie", "Kä\u00ADpy\u00ADlän\u00ADtie");
        map.put("Mannerheimintie", "Man\u00ADner\u00ADhei\u00ADmin\u00ADtie");
        map.put("Pohjolankatu", "Poh\u00ADjo\u00ADlan\u00ADka\u00ADtu");
        map.put("Narinkka", "Na\u00ADrink\u00ADka");
        map.put("Pohjolanaukio", "Poh\u00ADjo\u00ADlan\u00ADau\u00ADki\u00ADo");
        map.put("Kampin metroasema", "Kam\u00ADpin met\u00ADro\u00ADa\u00ADse\u00ADma");
        map.put("Käpylän asema", "Kä\u00ADpy\u00ADlän a\u00ADse\u00ADma");
        map.put("Eerikinkatu", "Ee\u00ADri\u00ADkin\u00ADka\u00ADtu");
        map.put("Juhana Herttuan tie", "Ju\u00ADha\u00ADna Hert\u00ADtu\u00ADan tie");
        map.put("Lastenlehto", "Las\u00ADten\u00ADleh\u00ADto");
        map.put("Toinen linja", "Toi\u00ADnen lin\u00ADja");
        map.put("Baana", "Baa\u00ADna");
        map.put("Töölönlahden puisto", "Töö\u00ADlön\u00ADlah\u00ADden puis\u00ADto");
        map.put("Itämerentori", "I\u00ADtä\u00ADme\u00ADren\u00ADto\u00ADri");
        map.put("Marian Sairaala", "Ma\u00ADri\u00ADan Sai\u00ADraa\u00ADla");
        map.put("Eläinmuseo", "E\u00ADläin\u00ADmu\u00ADse\u00ADo");
        map.put("Kauppakorkeakoulu", "Kaup\u00ADpa\u00ADkor\u00ADke\u00ADa\u00ADkou\u00ADlu");
        map.put("Kansallismuseo", "Kan\u00ADsal\u00ADlis\u00ADmu\u00ADse\u00ADo");
        map.put("Cygnauksenkatu", "Cyg\u00ADnauk\u00ADsen\u00ADka\u00ADtu");
        map.put("Apollonkatu", "A\u00ADpol\u00ADlon\u00ADka\u00ADtu");
        map.put("Töölönkatu", "Töö\u00ADlön\u00ADka\u00ADtu");
        map.put("Töölöntori", "Töö\u00ADlön\u00ADto\u00ADri");
        map.put("Ooppera", "Oop\u00ADpe\u00ADra");
        map.put("Hakaniemen metroasema", "Ha\u00ADka\u00ADnie\u00ADmen met\u00ADro\u00ADa\u00ADse\u00ADma");
        map.put("Eteläesplanadi", "E\u00ADte\u00ADlä\u00ADesp\u00ADla\u00ADna\u00ADdi");
        map.put("Ympyrätalo", "Ym\u00ADpy\u00ADrä\u00ADta\u00ADlo");
        map.put("Leppäsuonaukio", "Lep\u00ADpä\u00ADsuon\u00ADau\u00ADki\u00ADo");
        map.put("Haapaniemenkatu", "Haa\u00ADpa\u00ADnie\u00ADmen\u00ADka\u00ADtu");
        map.put("Lehtisaarentie", "Leh\u00ADti\u00ADsaa\u00ADren\u00ADtie");
        map.put("Karhupuisto", "Kar\u00ADhu\u00ADpuis\u00ADto");
        map.put("Sörnäisten metroasema", "Sör\u00ADnäis\u00ADten met\u00ADro\u00ADa\u00ADse\u00ADma");
        map.put("Brahen kenttä", "Bra\u00ADhen kent\u00ADtä");
        map.put("Diakoniapuisto", "Di\u00ADa\u00ADko\u00ADni\u00ADa\u00ADpuis\u00ADto");
        map.put("Vanha Kauppahalli", "Van\u00ADha Kaup\u00ADpa\u00ADhal\u00ADli");
        map.put("Mastokatu", "Mas\u00ADto\u00ADka\u00ADtu");
        map.put("Annankatu", "An\u00ADnan\u00ADka\u00ADtu");
        map.put("Nokkala", "Nok\u00ADka\u00ADla");
        map.put("Matinlahdenranta", "Ma\u00ADtin\u00ADlah\u00ADden\u00ADran\u00ADta");
        map.put("Nuottaniementie", "Nuot\u00ADta\u00ADnie\u00ADmen\u00ADtie");
        map.put("Sepetlahdentie", "Se\u00ADpet\u00ADlah\u00ADden\u00ADtie");
        map.put("Melkonkuja", "Mel\u00ADkon\u00ADku\u00ADja");
        map.put("Itälahdenkatu", "I\u00ADtä\u00ADlah\u00ADden\u00ADka\u00ADtu");
        map.put("Heikkilänaukio", "Heik\u00ADki\u00ADlän\u00ADau\u00ADki\u00ADo");
        map.put("Heikkiläntie", "Heik\u00ADki\u00ADlän\u00ADtie");
        map.put("Gyldenintie", "Gyl\u00ADde\u00ADnin\u00ADtie");
        map.put("Puistokaari", "Puis\u00ADto\u00ADkaa\u00ADri");
        map.put("Luoteisväylä", "Luo\u00ADteis\u00ADväy\u00ADlä");
        map.put("Lauttasaaren ostoskeskus", "Laut\u00ADta\u00ADsaa\u00ADren os\u00ADtos\u00ADkes\u00ADkus");
        map.put("Lauttasaarensilta", "Laut\u00ADta\u00ADsaa\u00ADren\u00ADsil\u00ADta");
        map.put("Salmisaarenranta", "Sal\u00ADmi\u00ADsaa\u00ADren\u00ADran\u00ADta");
        map.put("Matinkartanontie", "Ma\u00ADtin\u00ADkar\u00ADta\u00ADnon\u00ADtie");
        map.put("Matinkyläntie", "Ma\u00ADtin\u00ADky\u00ADlän\u00ADtie");
        map.put("Tiistiläntie", "Tiis\u00ADti\u00ADlän\u00ADtie");
        map.put("Tiistinkallio", "Tiis\u00ADtin\u00ADkal\u00ADli\u00ADo");
        map.put("Etuniementie", "E\u00ADtu\u00ADnie\u00ADmen\u00ADtie");
        map.put("Porkkalankatu", "Pork\u00ADka\u00ADlan\u00ADka\u00ADtu");
        map.put("Länsisatamankatu", "Län\u00ADsi\u00ADsa\u00ADta\u00ADman\u00ADka\u00ADtu");
        map.put("Messitytönkatu", "Mes\u00ADsi\u00ADty\u00ADtön\u00ADka\u00ADtu");
        map.put("Jätkäsaarenlaituri", "Jät\u00ADkä\u00ADsaa\u00ADren\u00ADlai\u00ADtu\u00ADri");
        map.put("Tyynenmerenkatu", "Tyy\u00ADnen\u00ADme\u00ADren\u00ADka\u00ADtu");
        map.put("Hylkeenpyytäjänkatu", "Hyl\u00ADkeen\u00ADpyy\u00ADtä\u00ADjän\u00ADka\u00ADtu");
        map.put("Ehrenströmintie", "Eh\u00ADrenst\u00ADrö\u00ADmin\u00ADtie");
        map.put("Perämiehenkatu", "Pe\u00ADrä\u00ADmie\u00ADhen\u00ADka\u00ADtu");
        map.put("Albertinkatu", "Al\u00ADber\u00ADtin\u00ADka\u00ADtu");
        map.put("Kalevankatu", "Ka\u00ADle\u00ADvan\u00ADka\u00ADtu");
        map.put("Hauenkalliontie", "Hau\u00ADen\u00ADkal\u00ADli\u00ADon\u00ADtie");
        map.put("Nelikkotie", "Ne\u00ADlik\u00ADko\u00ADtie");
        map.put("Keilalahti", "Kei\u00ADla\u00ADlah\u00ADti");
        map.put("Suomenlahdentie", "Suo\u00ADmen\u00ADlah\u00ADden\u00ADtie");
        map.put("Westendinasema", "Wes\u00ADten\u00ADdi\u00ADna\u00ADse\u00ADma");
        map.put("Piispansilta", "Piis\u00ADpan\u00ADsil\u00ADta");
        map.put("Golfpolku", "Golf\u00ADpol\u00ADku");
        map.put("Piispanportti", "Piis\u00ADpan\u00ADport\u00ADti");
        map.put("Revontulentie", "Re\u00ADvon\u00ADtu\u00ADlen\u00ADtie");
        map.put("Sammonpuistikko", "Sam\u00ADmon\u00ADpuis\u00ADtik\u00ADko");
        map.put("Hietaniemenkatu", "Hie\u00ADta\u00ADnie\u00ADmen\u00ADka\u00ADtu");
        map.put("Eteläinen Hesperiankatu", "E\u00ADte\u00ADläi\u00ADnen Hes\u00ADpe\u00ADri\u00ADan\u00ADka\u00ADtu");
        map.put("Kesäkatu", "Ke\u00ADsä\u00ADka\u00ADtu");
        map.put("Rajasaarentie", "Ra\u00ADja\u00ADsaa\u00ADren\u00ADtie");
        map.put("Korjaamo", "Kor\u00ADjaa\u00ADmo");
        map.put("Olympiastadion", "O\u00ADlym\u00ADpi\u00ADa\u00ADsta\u00ADdi\u00ADon");
        map.put("Nordenskiöldinaukio", "Nor\u00ADdens\u00ADki\u00ADöl\u00ADdi\u00ADnau\u00ADki\u00ADo");
        map.put("Messeniuksenkatu", "Mes\u00ADse\u00ADniuk\u00ADsen\u00ADka\u00ADtu");
        map.put("Uimastadion", "Ui\u00ADma\u00ADsta\u00ADdi\u00ADon");
        map.put("Friisilänaukio", "Frii\u00ADsi\u00ADlä\u00ADnau\u00ADki\u00ADo");
        map.put("Sateentie", "Sa\u00ADteen\u00ADtie");
        map.put("Avaruuskatu", "A\u00ADva\u00ADruus\u00ADka\u00ADtu");
        map.put("Hakalehto", "Ha\u00ADka\u00ADleh\u00ADto");
        map.put("Kuunkatu", "Kuun\u00ADka\u00ADtu");
        map.put("Oravannahkatori", "O\u00ADra\u00ADvan\u00ADnah\u00ADka\u00ADto\u00ADri");
        map.put("Ruomelantie", "Ruo\u00ADme\u00ADlan\u00ADtie");
        map.put("Länsituuli", "Län\u00ADsi\u00ADtuu\u00ADli");
        map.put("Itäportti", "I\u00ADtä\u00ADport\u00ADti");
        map.put("Tapionaukio", "Ta\u00ADpi\u00ADon\u00ADau\u00ADki\u00ADo");
        map.put("Jäähalli", "Jää\u00ADhal\u00ADli");
        map.put("Stenbäckinkatu", "Sten\u00ADbäc\u00ADkin\u00ADka\u00ADtu");
        map.put("Töölöntulli", "Töö\u00ADlön\u00ADtul\u00ADli");
        map.put("Meilahden sairaala", "Mei\u00ADlah\u00ADden sai\u00ADraa\u00ADla");
        map.put("Mäntytie", "Män\u00ADty\u00ADtie");
        map.put("Jalavatie", "Ja\u00ADla\u00ADva\u00ADtie");
        map.put("Kuusitie", "Kuu\u00ADsi\u00ADtie");
        map.put("Kustaankatu", "Kus\u00ADtaan\u00ADka\u00ADtu");
        map.put("Kiskontie", "Kis\u00ADkon\u00ADtie");
        map.put("Tilkanvierto", "Til\u00ADkan\u00ADvier\u00ADto");
        map.put("Komeetankatu", "Ko\u00ADmee\u00ADtan\u00ADka\u00ADtu");
        map.put("Kulttuuriaukio", "Kult\u00ADtuu\u00ADri\u00ADau\u00ADki\u00ADo");
        map.put("Auringonkatu", "Au\u00ADrin\u00ADgon\u00ADka\u00ADtu");
        map.put("Ahertajantie", "A\u00ADher\u00ADta\u00ADjan\u00ADtie");
        map.put("Piispankallio", "Piis\u00ADpan\u00ADkal\u00ADli\u00ADo");
        map.put("Mäntyviita", "Män\u00ADty\u00ADvii\u00ADta");
        map.put("Lystimäki", "Lys\u00ADti\u00ADmä\u00ADki");
        map.put("Otsolahti", "Ot\u00ADso\u00ADlah\u00ADti");
        map.put("Keilaniemi (M)", "Kei\u00ADla\u00ADnie\u00ADmi (M)");
        map.put("Paciuksenkaari", "Pa\u00ADciuk\u00ADsen\u00ADkaa\u00ADri");
        map.put("Seurasaari", "Seu\u00ADra\u00ADsaa\u00ADri");
        map.put("Saunalahdentie", "Sau\u00ADna\u00ADlah\u00ADden\u00ADtie");
        map.put("Torpanranta", "Tor\u00ADpan\u00ADran\u00ADta");
        map.put("Laajalahden aukio", "Laa\u00ADja\u00ADlah\u00ADden au\u00ADki\u00ADo");
        map.put("Munkkiniemen aukio", "Munk\u00ADki\u00ADnie\u00ADmen au\u00ADki\u00ADo");
        map.put("Huopalahdentie", "Huo\u00ADpa\u00ADlah\u00ADden\u00ADtie");
        map.put("Ulvilantie", "Ul\u00ADvi\u00ADlan\u00ADtie");
        map.put("Muusantori", "Muu\u00ADsan\u00ADto\u00ADri");
        map.put("Suurpellonaukio", "Suur\u00ADpel\u00ADlon\u00ADau\u00ADki\u00ADo");
        map.put("Keilaranta", "Kei\u00ADla\u00ADran\u00ADta");
        map.put("Lukutori", "Lu\u00ADku\u00ADto\u00ADri");
        map.put("Tekniikantie", "Tek\u00ADnii\u00ADkan\u00ADtie");
        map.put("Innopoli", "In\u00ADno\u00ADpo\u00ADli");
        map.put("Aalto-yliopisto (M), Tietotie", "Aal\u00ADto-y\u00ADli\u00ADo\u00ADpis\u00ADto (M), Tie\u00ADto\u00ADtie");
        map.put("Aalto-yliopisto (M), Korkeakouluaukio", "Aal\u00ADto-y\u00ADli\u00ADo\u00ADpis\u00ADto (M), Kor\u00ADke\u00ADa\u00ADkou\u00ADlu\u00ADau\u00ADki\u00ADo");
        map.put("Otaranta", "O\u00ADta\u00ADran\u00ADta");
        map.put("Sähkömies", "Säh\u00ADkö\u00ADmies");
        map.put("Jämeräntaival", "Jä\u00ADme\u00ADrän\u00ADtai\u00ADval");
        map.put("Tietäjä", "Tie\u00ADtä\u00ADjä");
        map.put("Metsänneidonpolku", "Met\u00ADsän\u00ADnei\u00ADdon\u00ADpol\u00ADku");
        map.put("Kalevalantie", "Ka\u00ADle\u00ADva\u00ADlan\u00ADtie");
        map.put("Louhentori", "Lou\u00ADhen\u00ADto\u00ADri");
        map.put("Pohjankulma", "Poh\u00ADjan\u00ADkul\u00ADma");
        map.put("Koivu-Mankkaa", "Koi\u00ADvu-Mank\u00ADkaa");
        map.put("Mankkaanlaaksontie", "Mank\u00ADkaan\u00ADlaak\u00ADson\u00ADtie");
        map.put("Mankkaanaukio", "Mank\u00ADkaan\u00ADau\u00ADki\u00ADo");
        map.put("Tapiolan urheilupuisto", "Ta\u00ADpi\u00ADo\u00ADlan ur\u00ADhei\u00ADlu\u00ADpuis\u00ADto");
        map.put("Urheilupuisto (M)", "Ur\u00ADhei\u00ADlu\u00ADpuis\u00ADto (M)");
        map.put("Tontunmäentie", "Ton\u00ADtun\u00ADmä\u00ADen\u00ADtie");
        map.put("Olarinluoma", "O\u00ADla\u00ADrin\u00ADluo\u00ADma");
        map.put("Niittymaa", "Niit\u00ADty\u00ADmaa");
        map.put("Niittykumpu (M)", "Niit\u00ADty\u00ADkum\u00ADpu (M)");
        map.put("Haukilahdenkatu", "Hau\u00ADki\u00ADlah\u00ADden\u00ADka\u00ADtu");
        map.put("Teljäntie", "Tel\u00ADjän\u00ADtie");
        map.put("Munkkivuoren ostoskeskus", "Munk\u00ADki\u00ADvuo\u00ADren os\u00ADtos\u00ADkes\u00ADkus");
        map.put("Haukilahdenaukio", "Hau\u00ADki\u00ADlah\u00ADden\u00ADau\u00ADki\u00ADo");
        map.put("Vihdintie", "Vih\u00ADdin\u00ADtie");
        map.put("Hauenkallio", "Hau\u00ADen\u00ADkal\u00ADli\u00ADo");
        map.put("Kriikunakuja", "Krii\u00ADku\u00ADna\u00ADku\u00ADja");
        map.put("Tilkantori", "Til\u00ADkan\u00ADto\u00ADri");
        map.put("Haukilahdenranta", "Hau\u00ADki\u00ADlah\u00ADden\u00ADran\u00ADta");
        map.put("Korppaanmäentie", "Korp\u00ADpaan\u00ADmä\u00ADen\u00ADtie");
        map.put("Tenholantie", "Ten\u00ADho\u00ADlan\u00ADtie");
        map.put("Radiokatu", "Ra\u00ADdi\u00ADo\u00ADka\u00ADtu");
        map.put("Hertanmäenkatu", "Her\u00ADtan\u00ADmä\u00ADen\u00ADka\u00ADt");
        stationHyphenations = Collections.unmodifiableMap(map);
    }

    public static String hyphenateStation(String station) {
        if (stationHyphenations.containsKey(station)) {
            return stationHyphenations.get(station);
        }
        else {
            return station;
        }
    }
}
